### PR TITLE
Improved reward function

### PR DESCRIPTION
**Pull request by 222464**
Hi,

I have been using this gym interface for a few races, but I always had to hack around the reward being based on speed instead of forward velocity (speed is always positive). As a result, an RL agent must be constrained to only be able to drive forwards, as otherwise it can get a reward by driving backwards (undesirable) on the track. This PR adds a new value called forward_vel that is equivalent to a signed version of speed. It also modifies the default reward function to use it.

With this change, actions must no longer be constrained, as going in reverse gives a negative reward. Going forward still uses the centering reward, which I don't think helps really but I kept it anyways. Since the actions no longer need to be constrained, the agent can freely reverse in order to break in sharp turns, for instance.

Tested on Python 3.9, so I bumped that up as well.

### CODE REVIEW

**Comment by tawnkramer** [comment]
In general the reward function is super important and should be customized by any user of gym donkeycar. However it is expected that most will use the provided api to override the default function with their own: DonkeyEnv::SetRewardFunction. Perhaps the docs need to specify that. I wanted not the perfect reward function but only the most basic, leaving room for improvement.

**Comment by 222464** [comment]
Hi,

I feel like the default reward should at the very least somewhat mimic the desired objective, though. As it is right now, the car gets rewarded for driving backwards as much as forwards. The reward function isn't so much "sub-optimal" as it is just not aligned with the desired outcome at all. Would you be okay with keeping just the forward_vel bit (velocity in the forward direction)? There is essentially no way a reward function doesn't end up using something like it.

**Comment by tawnkramer** [comment]
I agree. I will merge this.

**Comment by tawnkramer** [comment]
Are you able to fix this?

https://github.com/tawnkramer/gym-donkeycar/actions/runs/3769530436/jobs/6408800107

**Comment by 222464** [comment]
Sure, will fix!

**Comment by 222464** [comment]
Hmm, looking at the diff to the last commit before the merge, I don't see anything that would generate this error. Has the type checker perhaps become more strict (since the previous commit was months ago)? I will keep looking...

[diff](https://github.com/tawnkramer/gym-donkeycar/compare/4ea670491eaef66178a1ffe3d672c7d4344c51bf..master)

**Comment by tawnkramer** [comment]
Ok. I will take a look later.

**Comment by araffin** [comment]
type check failing can be also due to an update to pytype

**Pull request merged**
