### PR TITLE
Added a lap counter to the info dictionary returned by the gym.

### PR DESCRIPTION
**Pull request by Bleyddyn**
In trying to create a more automated testing tool, I wanted to be able to count laps completed and none of the existing code seemed to work. See this commit for an example of how I'm using it: https://github.com/Bleyddyn/malpi/commit/e7d2c43a840e3d9260cfd65a062e1bcddb9bbdb4

I don't see any way to create issues on this repo, so I'm just doing a pull request. If there's someplace I should add documentation about the change, let me know.

### CODE REVIEW

**Comment by Maximellerbach** [comment]
lgtm, could you just format you code using the following command:```black -l 127 .```
or ```make format```.
Thanks !

**Comment by Bleyddyn** [comment]
That didn't change any files. The build error did seem odd because it was talking about a file I hadn't changed.

```
$ make format
# Sort imports
isort gym_donkeycar/ tests/ docs/conf.py setup.py examples/
# Reformat using black
black -l 127 gym_donkeycar/ tests/ docs/conf.py setup.py examples/
All done! ✨ 🍰 ✨
27 files left unchanged.
```
```
$ git status
On branch lap_count
Your branch is up to date with 'origin/lap_count'.

nothing to commit, working tree clean
```

**Comment by Maximellerbach** [comment]
indeed it's weird, I think it's ready to merge then. 
@tawnkramer what do you think ?

**Review by Maximellerbach — APPROVED** [review]

**Comment by tawnkramer** [comment]
it looks like 
```
black --check -l 127 gym_donkeycar/ tests/ docs/conf.py setup.py examples/
would reformat docs/conf.py
```

will only make changes in 3.6. my guess is Andrew checked in 3.7+ ?

**Comment by Bleyddyn** [comment]
I'm using python 3.9

**Comment by Maximellerbach** [comment]
Anyway, I think it should be good, I don't see why the tests are not passing. @tawnkramer good for merging ?

**Comment by araffin** [comment]
> That didn't change any files

You need latest black version

**Comment by Bleyddyn** [comment]
> > That didn't change any files
> 
> You need latest black version

apt-get says that's what I'm using:

```
$ black --version
black, version 20.8b1

$ sudo apt-get install --upgrade black
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
black is already the newest version (20.8b1-4).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by araffin** [comment]
> apt-get says that's what I'm using:

apt is for debian binaries and package are not often updated (unless you are using custom ppa), you should be using pip (python packet manager) to install black.

Latest black version: black==22.1.0
See https://pypi.org/project/black/

**Comment by Bleyddyn** [comment]
Switched to using pip installed black and it worked. Still doesn't explain why a file I didn't change needed to be re-formatted.

**Comment by araffin** [comment]
> Still doesn't explain why a file I didn't change needed to be re-formatted.

Black may change the formatting from one version to another (happens only once a year).

https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy

**Pull request merged**
